In [2]:
print("Hello Major!!!")
a=10
b=10
c=a+b
print(c)

Hello Major!!!
20


In [1]:
import numpy as t

arr = t.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
print(np.__version__)

2.1.3


In [7]:
import numpy as np

arr = np.array(42)

print(arr)
print(type(arr))


42
<class 'numpy.ndarray'>


In [9]:
import numpy as np

arr = np.array([42])

print(arr)
print(type(arr))

[42]
<class 'numpy.ndarray'>


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,12])

newarr = arr.reshape(3, 4)

print(newarr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [1]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [1]:
y = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = y.keys()

print(x)


dict_keys(['brand', 'model', 'year'])


In [3]:
day = 4
match day:
  case 1:
    print("Monday")
  case 2:
    print("Tuesday")
  case 3:
    print("Wednesday")
  case 4:
    print("Thursday")
  case 5:
    print("Friday")
  case 6:
    print("Saturday")
  case 7:
    print("Sunday")


Thursday


In [4]:
for x in range(6):
  if x == 3: 
    break
  print(x)
else:
  print("Finally finished!")

#If the loop breaks, the else block is not executed.


0
1
2


In [2]:
x="Parth"
for i in x:
  print(i)

P
a
r
t
h


In [1]:
def add(a, b):  # a and b are parameters
    return a + b

result = add(5, 3)  # 5 and 3 are arguments
print(result)


8


In [4]:
nums = [1,2,3,4,5]
for num in nums:
    if num==3:
     break
else:
    ("Completed")

In [16]:
def print_names(*names):
        print("Hello,", names)

print_names("Alice","Shlok")


Hello, ('Alice', 'Shlok')


In [17]:
def log_message(*messages):
    for msg in messages:
        print("[LOG]:", msg)

log_message("Start process", "Loading data", "Process completed")


[LOG]: Start process
[LOG]: Loading data
[LOG]: Process completed


In [20]:
def multiply(*nums):
    result = 1
    for n in nums:
        result *= n
    return result

print(multiply(2, 3, 4)) # 24


24


In [21]:
a = int("12")
b = int("6")
print(a==b)

False


In [1]:
def send_email(to, subject, body, cc=None, bcc=None, priority="Normal"):
    print(f"Sending email:")
    print(f"To: {to}")
    print(f"Subject: {subject}")
    print(f"Body: {body}")
    print(f"CC: {cc}")
    print(f"BCC: {bcc}")
    print(f"Priority: {priority}")
    print("Email sent successfully!\n")

# ✅ Using positional arguments
send_email("alice@example.com", "Meeting", "Please attend the meeting at 5 PM.")

# ✅ Using keyword arguments (clear, flexible order)
send_email(
    subject="Reminder",
    to="bob@example.com",
    body="Don't forget to submit the report.",
    priority="High",
    cc="manager@example.com"
)

# ✅ Mixing positional and keyword (positional first)
send_email("carol@example.com", "Greetings", "Happy Birthday!", priority="Low")


Sending email:
To: alice@example.com
Subject: Meeting
Body: Please attend the meeting at 5 PM.
CC: None
BCC: None
Priority: Normal
Email sent successfully!

Sending email:
To: bob@example.com
Subject: Reminder
Body: Don't forget to submit the report.
CC: manager@example.com
BCC: None
Priority: High
Email sent successfully!

Sending email:
To: carol@example.com
Subject: Greetings
Body: Happy Birthday!
CC: None
BCC: None
Priority: Low
Email sent successfully!



In [2]:
def order_pizza(customer, size="Medium", crust="Regular", toppings=None, extra_cheese=False):
    if toppings is None:
        toppings = []
    print(f"Order Summary for {customer}:")
    print(f"- Size: {size}")
    print(f"- Crust: {crust}")
    print(f"- Toppings: {', '.join(toppings) if toppings else 'No extra toppings'}")
    print(f"- Extra Cheese: {'Yes' if extra_cheese else 'No'}")
    print("Your pizza will be ready soon!\n")

# ✅ Using only defaults + positional
order_pizza("Alice")

# ✅ Using keyword arguments for clarity
order_pizza(
    customer="Bob",
    size="Large",
    crust="Thin",
    toppings=["Pepperoni", "Olives"],
    extra_cheese=True
)

# ✅ Mix positional and keyword
order_pizza("Charlie", toppings=["Mushrooms", "Paneer"])


Order Summary for Alice:
- Size: Medium
- Crust: Regular
- Toppings: No extra toppings
- Extra Cheese: No
Your pizza will be ready soon!

Order Summary for Bob:
- Size: Large
- Crust: Thin
- Toppings: Pepperoni, Olives
- Extra Cheese: Yes
Your pizza will be ready soon!

Order Summary for Charlie:
- Size: Medium
- Crust: Regular
- Toppings: Mushrooms, Paneer
- Extra Cheese: No
Your pizza will be ready soon!



In [3]:
letters = ["P", "y", "t", "h", "o", "n"]
print("".join(letters))
#without any seperator

Python


In [4]:
letters = ["P", "y", "t", "h", "o", "n"]
print(", ".join(letters))
# with ','(comma) as a seperator

P, y, t, h, o, n


In [5]:
def my_function(food):
  for x in food:
    print(x)

fruits = ["apple", "banana", "cherry"]

my_function(fruits)


apple
banana
cherry


In [7]:
def data(x):
 return x*8
print (data(3))
print (data(4))

24
32


In [8]:
def transfer(from_account, to_account, /, amount, *, currency="USD", instant=False):
    print(f"Transferring {amount} {currency} from {from_account} to {to_account}. Instant: {instant}")

transfer("A123", "B456", 500, currency="EUR", instant=True)  # ✅
# transfer(from_account="A123", to_account="B456", amount=500) # ❌ positional-only
# transfer("A123", "B456", 500, "EUR", True)                  # ❌ keyword-only


Transferring 500 EUR from A123 to B456. Instant: True


In [9]:
x = 3>2
y = 5<1
print (x,y)

True False


In [10]:
def rec(n):
 if (n==0):
    return
 print (n)
 rec (n-1)
 print("END")

rec (4)

4
3
2
1
END
END
END
END


In [12]:
def fact(n):
 if (n==0 or n==1):
    return 1
 else :
  return n*fact(n-1)
fact (4)

24

In [19]:
def nat(n):
    if (n==0):
        return 0
    else:
        return n + nat(n-1)
nat(5)        

15

In [20]:
lst = [10,20,30]
print(len(lst))

3


In [33]:
def size(lst, index=0):
    if index == len(lst):
        return
    else:
        print(lst[index])
        size(lst, index+1)

size([10,20,30])


10
20
30


In [36]:
sq=lambda x:x*x       #Single Arguement
print(sq(5))


add=lambda x,y : x+y       #Multiple Arguement
print(add(2,3))


msg=lambda:"Shlok"        #No Arguement
print (msg())

25
5
Shlok


In [37]:
# Small Cheatsheet for LAMBDA

# With lambda
list(map(lambda x: x+10, [1,2,3]))   # [11,12,13]

# With def
def add10(x): return x+10
list(map(add10, [1,2,3]))  # [11,12,13]


[11, 12, 13]

In [38]:
def tri_recursion(k):
    if k > 0:
        print(f"Level {k}")
        tri_recursion(k - 1)
        tri_recursion(k - 1)
        tri_recursion(k - 1)
tri_recursion(3)


Level 3
Level 2
Level 1
Level 1
Level 1
Level 2
Level 1
Level 1
Level 1
Level 2
Level 1
Level 1
Level 1


In [1]:
class Person:
    pass

p = Person()
print(p.name)  # ❌ AttributeError


AttributeError: 'Person' object has no attribute 'name'

In [1]:
import sys
print(sys.executable)

D:\Jupyter\lab_env\Scripts\python.exe


In [2]:
import sys
print("Executable:", sys.executable)
print("Base Prefix:", sys.base_prefix)
print("Prefix:", sys.prefix)
print("Is venv?", sys.prefix != sys.base_prefix)


Executable: D:\Jupyter\lab_env\Scripts\python.exe
Base Prefix: D:\Python312
Prefix: D:\Jupyter\lab_env
Is venv? True


In [ ]:
class fraction:
    def__init__(self,n,d):
     self.num=n
     self.den=d

In [ ]:
name1='Shlok'
name1_age=20
name1_sal=100000

In [1]:
import platform

x = dir(platform)
print(x)


['_Processor', '_WIN32_CLIENT_RELEASES', '_WIN32_SERVER_RELEASES', '__builtins__', '__cached__', '__copyright__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', '_comparable_version', '_default_architecture', '_follow_symlinks', '_get_machine_win32', '_java_getprop', '_mac_ver_xml', '_node', '_norm_version', '_os_release_cache', '_os_release_candidates', '_parse_os_release', '_platform', '_platform_cache', '_sys_version', '_sys_version_cache', '_syscmd_file', '_syscmd_ver', '_uname_cache', '_unknown_as_blank', '_ver_stages', '_win32_ver', '_wmi', '_wmi_query', 'architecture', 'collections', 'freedesktop_os_release', 'functools', 'itertools', 'java_ver', 'libc_ver', 'mac_ver', 'machine', 'node', 'os', 'platform', 'processor', 'python_branch', 'python_build', 'python_compiler', 'python_implementation', 'python_revision', 'python_version', 'python_version_tuple', 're', 'release', 'sys', 'system', 'system_alias', 'uname', 'uname_result', 'version

In [3]:
class Udaipur:
    def Shlok(self):
     print("Gyan Nagar")

human = Udaipur()    #Creating object named human for the Udaipur class
human.Shlok()     #Calling its Method

human2 = Udaipur()
human2.Shlok()

Gyan Nagar
Gyan Nagar


In [5]:
class Udaipur:
    def Shlok(self):
     print("Gyan Nagar")

human = Udaipur()    #Creating object named human for the Udaipur class
human.Shlok()     #Calling its Method

human2 = Udaipur()
human2.Shlok()

Gyan Nagar
Gyan Nagar


In [7]:
class Students:
    def __init__(self):
        print("Creating new  student")

s1 = Students() 

Creating new  student


In [13]:
class Students:
    def __init__(self,fullname):
        self.name=fullname
        print("Creating new  student")

s1 = Students("Shlok") 
s1.name

Creating new  student


'Shlok'

In [1]:
import sys
print (sys.executable)

D:\Jupyter\lab_env\Scripts\python.exe


In [15]:
class User:
    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = password

    def say_hi_to_user(self, user):
        print(f"Sending message to {user.username}: Hi {user.username}, it's {self.username}")
user1 = User("Shlok", "shlok.nandwana@gmail.com", 123)
user2 = User("Sandhya", "sandhya_deora@gmail.com", 456)


user1.say_hi_to_user(user2)
user2.email
user2.username




#Because user2.email is the last evaluated expression, Python’s interactive shell automatically echoes it and this happens only in Jupyter/REPL not in .py file

Sending message to Sandhya: Hi Sandhya, it's Shlok


'Sandhya'

In [10]:
class User:
    def __init__(self, username, email, password):   # __init__ is the constructor which runs automatically when new object of class is created
        self.username = username                     # saves the username value in the object
        self._email = email                        #  _ is used to make data attribute protected 
        self.password = password

    def clean_email(self):
     return self._email.lower().strip()
        
user1 = User("Shlok", "Shlok.nandwana@gmail.com     ", 123)      #user1 and user2 are objects of user class
user2 = User("Sandhya", "Sandhya_deora@gmail.com", 456)

print(user1._email)                                # We can still do instance._email from outside the class and Python won’t stop you.
print(user1.clean_email())
print(user2.clean_email())



#Because user2.email is the last evaluated expression, Python’s interactive shell automatically echoes it and this happens only in Jupyter/REPL not in .py file

Shlok.nandwana@gmail.com     
shlok.nandwana@gmail.com
sandhya_deora@gmail.com


In [11]:
#Protected Variable
class Student:
    def __init__(self, name, age):
        self._age = age   # protected (by convention)

s = Student("Shlok", 21)
print(s._age)  # ⚠️ Technically works, but discouraged


21


In [12]:
#Private Variable
class Student:
    def __init__(self, name, age):
        self.__age = age   # private (name-mangled)

s = Student("Shlok", 21)
# print(s.__age)  # ❌ AttributeError
print(s._Student__age)  # ✅ Works (name-mangling)


21


In [13]:
#Getters/Setters
class Student:
    def __init__(self, name, age):
        self.__age = age   # private storage

    @property
    def age(self):   # getter
        return self.__age

    @age.setter
    def age(self, value):  # setter
        if value < 0:
            raise ValueError("Age cannot be negative")
        self.__age = value

s = Student("Shlok", 21)
print(s.age)   # ✅ uses getter
s.age = 25     # ✅ uses setter
# s.age = -5   # ❌ ValueError

21


In [16]:
class User:
    def __init__(self, username, email, password):   # __init__ is the constructor which runs automatically when new object of class is created
        self.username = username                     # saves the username value in the object
        self._email = email                        #  _ is used to make data attribute protected 
        self.password = password
        
    def get_email(self):                    #get_email is an instance method (requires self). It returns the current internal _email value exactly as stored (no cleaning happens here).
        return self._email

    def set_email(self, new_email):          #set_email sets/replaces the internal _email with whatever new_email you provide.
        self._email=new_email
        
user1 = User("Shlok", "Shlok.nandwana@gmail.com     ", 123)      #user1 and user2 are objects of user class
user2 = User("Sandhya", "Sandhya_deora@gmail.com", 456)

#print(user1.get_email())

#user1._email="123456"
user1.set_email("majornandwana131@gmail.com")
print(user1.get_email())

majornandwana131@gmail.com


In [21]:
from datetime import datetime

class User:
    def __init__(self, username, email, password):
        self.username = username
        self._email = None
        self.password = password
        self.email = email   # this will call the setter at creation

    @property
    def email(self):
        print(f"Email accessed at {datetime.now()}")
        return self._email

    @email.setter
    def email(self, new_email):
        cleaned = new_email.strip().lower()
        if "@" not in cleaned:
            raise ValueError("Invalid email")
        self._email = cleaned


# Usage
user1 = User("Shlok", "Shlok.nandwana@gmail.com     ", 123)
user1.email = " NEW@Example.COM "       # calls the setter
print(user1.email)                      # calls the getter, prints log + value


Email accessed at 2025-09-11 14:35:12.348538
new@example.com


In [39]:
y=2.0
print(y)
print(type(y))
z=int(y)
print(z)
print(type(z))

2.0
<class 'float'>
2
<class 'int'>


In [50]:
import random
print(random.randrange(5))

0


In [55]:
x=35e9
print(x)

35000000000.0


In [56]:
x=3
y=str(x)
print(type(y))

<class 'str'>


In [59]:
x='''x
y'''
print(x)

x
y


In [66]:
x="SHLOK     "
print(len(x))

10


In [11]:
x=float(10)
print(type(x))

<class 'float'>


In [14]:
x=y=z = 'a'
print(x,y,z)

a a a


In [26]:
alpha= ['1', 'b', 'c']
x,y,z = alpha
print(x+y+z)

1bc


1
